vcd:
  vipSubnet: "10.89.127.253/19" # Virtual IP CIDR for the external network
loadbalancer:
  ports:
    tcp: 6443
# managementClusterRDEId is the RDE ID of this management cluster if it exists; if this cluster is a child of another CAPVCD based cluster,
# an associated RDE will be created in VCD of Entity Type "urn:vcloud:type:vmware:capvcdCluster:1.0.0".
# Retrieve that RDEId using the API - https://VCD_IP/cloudapi/1.0.0/entities/types/vmware/capvcdCluster/1.0.0
managementClusterRDEId: ""
clusterResourceSet:
  csi: 1.2.0 # CSI version to be used in the workload cluster
  cpi: 1.1.1 # CPI version to be used in the workload cluster
